### ISSUE TITLE
Publish v1.0.1 to remove console?

### ISSUE THREAD

**Issue by chunkai1312** [eggjs-community/egg-passport-google#2]
I found that you have removed `console.log()` from `app.js` in the repository, but `egg-passport-google@1.0.0` on NPM still remains.

Can you publish a new version of the package to NPM for this issue?
Thanks.

**Comment by sinchang** [comment]
@chunkai1312 Done.

**Comment by chunkai1312** [comment]
@sinchang Thanks for your help!
