### ISSUE TITLE
Legacy People API has not been used in project 129322447526 before or it is disabled

### ISSUE THREAD

**Issue by jok311** [eggjs-community/egg-passport-google#4]
passport-google-oauth20 

这个库要升级到2.0了吧

**Comment by leoner** [comment]
https://stackoverflow.com/questions/58645078/403-message-legacy-people-api-has-not-been-used-in-project

![image](https://user-images.githubusercontent.com/546535/96692456-a2225000-13b8-11eb-8a8f-56f8bf291174.png)
